name: 'heroku-auth'
description: 'GitHub Action that adds your Heroku credentials to ~/.netrc for other jobs in your workflow.'
inputs:
  api_key:
    description: 'Your Heroku API key'
    required: true
  email:
    description: 'Your Heroku email address'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
