name: 'heroku-destroy'
description: 'GitHub Action that destroys an existing Heroku application.'
inputs:
  application_name:
    description: 'The name of the application you want to destroy'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
